// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUTA16bPvky5tgy4NpL1sBA0h5c5cEBk',
    appId: '1:174572746168:web:1a1448fae8c359eaa98b4d',
    messagingSenderId: '174572746168',
    projectId: 'striped-29d5a',
    authDomain: 'striped-29d5a.firebaseapp.com',
    storageBucket: 'striped-29d5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn8QSZrrZ4RiPL5a3Qi2HZKJ1UEDdeQWI',
    appId: '1:174572746168:android:fa925ce0d4bc7882a98b4d',
    messagingSenderId: '174572746168',
    projectId: 'striped-29d5a',
    storageBucket: 'striped-29d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBxLSIvGqzsS39BviqdRL5ZGwpDiTNKc',
    appId: '1:174572746168:ios:ad4f1ae6499a6aa7a98b4d',
    messagingSenderId: '174572746168',
    projectId: 'striped-29d5a',
    storageBucket: 'striped-29d5a.firebasestorage.app',
    iosBundleId: 'com.example.striped',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPUTA16bPvky5tgy4NpL1sBA0h5c5cEBk',
    appId: '1:174572746168:web:9774e5b6fe3e1232a98b4d',
    messagingSenderId: '174572746168',
    projectId: 'striped-29d5a',
    authDomain: 'striped-29d5a.firebaseapp.com',
    storageBucket: 'striped-29d5a.firebasestorage.app',
  );

}