// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDPUTA16bPvky5tgy4NpL1sBA0h5c5cEBk",
    authDomain: "striped-29d5a.firebaseapp.com",
    projectId: "striped-29d5a",
    storageBucket: "striped-29d5a.firebasestorage.app",
    messagingSenderId: "174572746168",
    appId: "1:174572746168:web:1a1448fae8c359eaa98b4d"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDPUTA16bPvky5tgy4NpL1sBA0h5c5cEBk",
    authDomain: "striped-29d5a.firebaseapp.com",
    projectId: "striped-29d5a",
    storageBucket: "striped-29d5a.firebasestorage.app",
    messagingSenderId: "174572746168",
    appId: "1:174572746168:web:1a1448fae8c359eaa98b4d"
  );
}
